### ISSUE TITLE
PLEASE JUST USE THE DOORS

### ISSUE THREAD

**Issue by TiberianEuan** [kolbytn/mindcraft#66]
![image](https://github.com/kolbytn/mindcraft/assets/46800751/e3386811-e01a-47f5-b9a8-cae3d7a9b46d)
GRAHH

**Comment by kolbytn** [comment]
This is a mineflayer issue, not a mindcraft issue. It is my number one feature request for the mineflayer pathfinder package.

**Comment by TiberianEuan** [comment]
okay then

uhh
are they working on fixing it over at mineflayer

**Comment by kolbytn** [comment]
There were several related issues a few years ago, but no updates since.
https://github.com/PrismarineJS/mineflayer-pathfinder/issues/12
https://github.com/PrismarineJS/mineflayer-pathfinder/issues/13
https://github.com/PrismarineJS/mineflayer-pathfinder/issues/20
https://github.com/PrismarineJS/mineflayer-pathfinder/issues/300

**Comment by TravnikovDev** [comment]
Yeah, that's super confusing problem 😞
